
package com.challenge.swiftcode.wsClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EntityManagementBeanService", targetNamespace = "http://www.sam.gov", wsdlLocation = "https://gw.sam.gov/SAMWS/1.0/Entity?wsdl")
public class EntityManagementBeanService
    extends Service
{

    private final static URL ENTITYMANAGEMENTBEANSERVICE_WSDL_LOCATION;
    private final static WebServiceException ENTITYMANAGEMENTBEANSERVICE_EXCEPTION;
    private final static QName ENTITYMANAGEMENTBEANSERVICE_QNAME = new QName("http://www.sam.gov", "EntityManagementBeanService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://gw.sam.gov/SAMWS/1.0/Entity?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENTITYMANAGEMENTBEANSERVICE_WSDL_LOCATION = url;
        ENTITYMANAGEMENTBEANSERVICE_EXCEPTION = e;
    }

    public EntityManagementBeanService() {
        super(__getWsdlLocation(), ENTITYMANAGEMENTBEANSERVICE_QNAME);
    }

    public EntityManagementBeanService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENTITYMANAGEMENTBEANSERVICE_QNAME, features);
    }

    public EntityManagementBeanService(URL wsdlLocation) {
        super(wsdlLocation, ENTITYMANAGEMENTBEANSERVICE_QNAME);
    }

    public EntityManagementBeanService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENTITYMANAGEMENTBEANSERVICE_QNAME, features);
    }

    public EntityManagementBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EntityManagementBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EntityManagementBean
     */
    @WebEndpoint(name = "EntityManagementBeanPort")
    public EntityManagementBean getEntityManagementBeanPort() {
        return super.getPort(new QName("http://www.sam.gov", "EntityManagementBeanPort"), EntityManagementBean.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EntityManagementBean
     */
    @WebEndpoint(name = "EntityManagementBeanPort")
    public EntityManagementBean getEntityManagementBeanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.sam.gov", "EntityManagementBeanPort"), EntityManagementBean.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENTITYMANAGEMENTBEANSERVICE_EXCEPTION!= null) {
            throw ENTITYMANAGEMENTBEANSERVICE_EXCEPTION;
        }
        return ENTITYMANAGEMENTBEANSERVICE_WSDL_LOCATION;
    }

}
