
package com.challenge.swiftcode.wsClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EntityManagementBean", targetNamespace = "http://www.sam.gov")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EntityManagementBean {


    /**
     * 
     * @param entitySearchCriteria
     * @param authenticationKey
     * @param requestedData
     * @return
     *     returns com.challenge.swiftcode.wsClient.GetEntities
     * @throws SystemException_Exception
     * @throws ApplicationException_Exception
     */
    @WebMethod
    @WebResult(name = "getEntities", partName = "getEntities")
    public GetEntities getEntities(
        @WebParam(name = "authenticationKey", partName = "authenticationKey")
        UserAuthenticationKeyType authenticationKey,
        @WebParam(name = "entitySearchCriteria", partName = "entitySearchCriteria")
        EntitySearchCriteriaType entitySearchCriteria,
        @WebParam(name = "requestedData", partName = "requestedData")
        RequestedData requestedData)
        throws ApplicationException_Exception, SystemException_Exception
    ;

}
